In [1]:
import numpy as np

In [2]:
a = np.array([10, 2, 3, 0, 3, 4, 0])

In [3]:
a.nonzero()

(array([0, 1, 2, 4, 5], dtype=int64),)

In [6]:
np.nonzero(a==3)

(array([2, 4], dtype=int64),)

In [7]:
np.where(a==3)

(array([2, 4], dtype=int64),)